### ISSUE TITLE
the MAP value range in  img_embeding/valid

### ISSUE THREAD

**Issue by XiaotianM** [toshi-k/kaggle-google-landmark-retrieval-challenge#1]
Hi, thank you for your nice work. Recently, I want to reproduce your work, and I want to check the map value range during validation phase when only using im_embeding features. Can you help me ? And how long  does it take about for training

**Comment by toshi-k** [comment]
The way to make validation set is important consideration in this competition. I make validation set with 10100 images (101 images x 100 classes) and calculate validation score by map 100. Please look at evaluator.py. Training took about 4~5 days.

https://github.com/toshi-k/kaggle-google-landmark-retrieval-challenge/blob/master/source/02_img_embedding/lib/evaluator.py#L18-L20
